import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Wacamole～ワカモレ～</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_provisional.png" />
      </Head>

      <main className={styles.main}>
      <Image src="/logo_provisional.png" alt="Wacamole" width={300} height={300} />
        <h1 className={styles.title}>
          Wacamoleへようこそ！
        </h1>
        <h1>Coming soon...</h1>

      </main>

      <footer className={styles.footer}>
        <a
          href="/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Wacamole 2022
          {/* <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
        </a>
      </footer>
    </div>
  )
}
